"""Type stubs for the `pyodide` package (Pyodide runtime in the browser)."""

from typing import Any

def eval_code(source: str, globals: dict | None = ..., locals: dict | None = ...) -> Any: ...
def eval_code_async(source: str, globals: dict | None = ..., locals: dict | None = ...) -> Any: ...
def runPython(source: str, globals: dict | None = ...) -> Any: ...
def runPythonAsync(source: str, globals: dict | None = ...) -> Any: ...

def get_value(obj: Any, key: str) -> Any: ...
def to_js(obj: Any, **kwargs: Any) -> Any: ...

class JsException(Exception):
    js_error: Any
