"""
@component decorator — turns a plain Python function into a Gluon component.

Two calling modes
-----------------
1. Inside a render tree (as a child):
       MyComponent(prop=value)
   Returns a VNode whose type is the original function.
   The renderer will later call the function with the fiber context set.

2. As the root argument to render():
       render(MyComponent, document.getElementById('root'))
   render() looks for the ._component_fn attribute to unwrap the wrapper.

Class-based fallback
--------------------
For components that are easier to express as classes, subclass Component
and implement render():

    class Clock(Component):
        def render(self):
            return div(p('…'))
"""

from __future__ import annotations

from typing import Any, Callable

from gluon.core.vdom import VNode, _flatten


def component(fn: Callable[..., Any]) -> Callable[..., VNode]:
    """
    Decorator: mark *fn* as a Gluon functional component.

    The returned wrapper, when called, creates a VNode rather than
    running the function immediately. The renderer will run *fn* at
    the right moment with the correct fiber context active.
    """
    def _call(*children: Any, **props: Any) -> VNode:
        key = props.pop('key', None)
        # children passed positionally end up in props['children']
        all_props = {**props, 'children': _flatten(children)}
        return VNode(fn, all_props, _flatten(children), key)

    _call._is_component = True  # type: ignore[attr-defined]
    _call._component_fn = fn        # renderer uses this to look up the fiber  # type: ignore[attr-defined]
    _call._is_server_component = getattr(fn, "_is_server_component", False)  # type: ignore[attr-defined]
    _call.__name__ = fn.__name__
    _call.__qualname__ = fn.__qualname__
    _call.__doc__ = fn.__doc__
    return _call


def server_component(fn: Callable[..., Any]) -> Callable[..., VNode]:
    """
    Decorator: mark *fn* as a Server-Side Only Gluon component.
    
    Server components are rendered to static HTML on the server.
    On the client, they are treated as static content and their hooks
    (if any) are not executed during hydration.
    """
    fn._is_server_component = True  # type: ignore[attr-defined]
    
    # We wrap the function to handle client-side hydration
    def hydration_wrapper(*args: Any, **kwargs: Any) -> Any:
        from gluon.runtime import is_browser, window
        
        if is_browser():
            # In the browser, try to find pre-rendered HTML from the server
            # Use only __name__ to match the stable ID generated by SSR
            comp_id = fn.__name__
            ssr_html = None
            
            if window and hasattr(window, "__GLUON_HYDRATION__"):
                hydration_map = window.__GLUON_HYDRATION__
                if hasattr(hydration_map, comp_id):
                    ssr_html = getattr(hydration_map, comp_id)
            
            if ssr_html is not None:
                # Return a VNode that just injects the static HTML
                from gluon.core.vdom import div
                return div(dangerouslySetInnerHTML={"__html": ssr_html})
        
        # On server (or if no hydration data found), run normally
        return fn(*args, **kwargs)

    # Copy metadata to wrapper
    hydration_wrapper.__name__ = fn.__name__
    hydration_wrapper.__qualname__ = fn.__qualname__
    hydration_wrapper.__doc__ = fn.__doc__
    hydration_wrapper._is_server_component = True  # type: ignore[attr-defined]

    return component(hydration_wrapper)


# ─── Class-based fallback ──────────────────────────────────────────────────────

class ComponentMeta(type):
    """Metaclass that makes Component subclasses behave like @component wrappers."""

    def __call__(cls, *children: Any, **props: Any) -> VNode | Component:  # type: ignore[override]
        # When used as MyComponent(prop=…) in a tree → return VNode
        if _is_in_render_tree():
            key = props.pop('key', None)
            all_props = {**props, 'children': _flatten(children)}
            # Use cls itself as the VNode type; renderer detects Component subclass
            return VNode(cls, all_props, _flatten(children), key)
        # Otherwise instantiate normally (e.g. render(MyComponent, root))
        return super().__call__(*children, **props)


def _is_in_render_tree() -> bool:
    """True when called during a render pass (fiber context is active)."""
    import gluon.core.fiber as _ctx
    return _ctx._current_fiber is not None


class Component(metaclass=ComponentMeta):
    """
    Base class for class-based components.

    Override render() to return a VNode tree.

    Example
    -------
        class Greeting(Component):
            def __init__(self, name='World'):
                self.name = name

            def render(self):
                return h1(f'Hello, {self.name}!')
    """

    # Marks the class so the renderer can identify it
    _is_component = True

    def __init__(self, **props: Any) -> None:
        self.props: dict[str, Any] = props

    def render(self) -> Any:
        raise NotImplementedError("Component subclasses must implement render()")
